# Generated by Django 5.1.15 on 2026-10-08 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentinel_api_keys", "0002_add_tenant_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
        ),
        migrations.AlterField(
            model_name="apikey",
            name="agent_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What this agent does. Used in audit reports and investigation.",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="agent_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Machine-readable agent name. e.g. 'support-bot', 'fraud-detector'",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="agent_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model or version identifier. e.g. 'gpt-4-turbo-2024-04', 'v2.1.3'",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="UTC timestamp when this record was created",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this key.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="UTC timestamp when this record was soft-deleted. Null if active.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When this key expires. Null = never expires.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier (UUIDv4, non-enumerable)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(
                help_text="HMAC-SHA256 hash of the full key. Used for verification.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key_prefix",
            field=models.CharField(
                db_index=True,
                help_text="First chars of the key for O(1) lookup. Not secret.",
                max_length=16,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True, help_text="When this key was last used for authentication.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="last_used_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP from which this key was last used.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(
                help_text="Human-readable name. e.g. 'Production Support Bot', 'Fraud Detector v3'",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="rotated_from",
            field=models.ForeignKey(
                blank=True,
                help_text="The key this was rotated from, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rotated_to",
                to="sentinel_api_keys.apikey",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="rotation_grace_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Old key remains valid until this time after rotation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="scopes",
            field=models.JSONField(
                default=list,
                help_text="List of permitted scopes. e.g. ['events:write', 'events:read', 'alerts:read']. Empty list = no permissions.",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="total_uses",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of authenticated requests using this key."
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="UTC timestamp when this record was last modified"
            ),
        ),
    ]
