# Generated by Django 5.1.15 on 2026-10-08 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentinel_tenants", "0002_add_tenant_id_to_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["name"],
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
            },
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="UTC timestamp when this record was created",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier (UUIDv4, non-enumerable)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="kafka_topic_prefix",
            field=models.CharField(
                blank=True, help_text="Auto-set on creation. sentinel.{tenant_id}", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="max_events_per_day",
            field=models.PositiveIntegerField(
                default=100000, help_text="Daily event ingestion limit. 0 = unlimited."
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(
                help_text="Organization name. e.g. 'Acme Fintech Ltd'", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="owner_email",
            field=models.EmailField(
                help_text="Primary contact for billing and critical alerts.", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe identifier. e.g. 'acme-fintech'", max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="UTC timestamp when this record was last modified"
            ),
        ),
    ]
