# Generated by Django 5.1.15 on 2026-10-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentinel_audit", "0004_reliable_signed_outbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="actor_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email snapshot at time of event. Denormalized for audit integrity — the user's email may change after the event.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="actor_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID of the authenticated user who performed this action. Null for unauthenticated events (e.g. failed login attempts).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("HUMAN", "Human User"),
                    ("SERVICE", "Backend Service"),
                    ("AI_AGENT", "AI Agent"),
                ],
                db_index=True,
                default="HUMAN",
                help_text="Type of actor: HUMAN, SERVICE, or AI_AGENT.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="agent_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Name of the AI agent or service. e.g. 'support-bot-v2', 'fraud-detector', 'gpt-4-reconciler'.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("USER_LOGIN", "User Login"),
                    ("USER_LOGOUT", "User Logout"),
                    ("USER_LOGIN_FAILED", "User Login Failed"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("USER_CREATED", "User Created"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_ROLE_CHANGED", "User Role Changed"),
                    ("API_KEY_CREATED", "API Key Created"),
                    ("API_KEY_ROTATED", "API Key Rotated"),
                    ("API_KEY_REVOKED", "API Key Revoked"),
                    ("TRANSFER_INITIATED", "Transfer Initiated"),
                    ("TRANSFER_APPROVED", "Transfer Approved"),
                    ("TRANSFER_REJECTED", "Transfer Rejected"),
                    ("ADMIN_ACTION", "Admin Action"),
                    ("PERMISSION_CHANGED", "Permission Changed"),
                    ("WEBHOOK_DELIVERED", "Webhook Delivered"),
                    ("WEBHOOK_FAILED", "Webhook Failed"),
                ],
                db_index=True,
                help_text="Categorized event type from AuditEventType enum.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="metadata",
            field=models.JSONField(
                default=dict,
                help_text="Structured context for this event. Schema varies by event_type.",
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="request_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="X-Request-ID of the HTTP request that produced this event.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="resource_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Identifier of the affected resource.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="resource_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Type of the affected resource (e.g. 'user', 'api_key', 'transfer').",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="risk_score",
            field=models.SmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Composite risk score 0-100 computed by the risk engine. Null until risk engine processes this event.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="signature",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HMAC-SHA256 signature over key event fields. Used for tamper detection.",
                max_length=64,
            ),
        ),
    ]
