# Generated by Django 5.1.15 on 2026-10-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sentinel_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentineluser",
            name="failed_login_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Consecutive failed login attempts since last success. Reset on login.",
            ),
        ),
        migrations.AlterField(
            model_name="sentineluser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="sentineluser",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Inactive users cannot authenticate. Use this instead of deletion.",
            ),
        ),
        migrations.AlterField(
            model_name="sentineluser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Grants access to Django admin. Should only be set for ADMIN role users.",
            ),
        ),
        migrations.AlterField(
            model_name="sentineluser",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of the most recent successful login.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sentineluser",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Force password change on next login (e.g. after admin reset).",
            ),
        ),
        migrations.AlterField(
            model_name="sentineluser",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the password was last changed. Used for forced rotation policies.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sentineluser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
