# Generated by Django 5.1.15 on 2026-10-08 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentinel_compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compliancereport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Compliance Report",
                "verbose_name_plural": "Compliance Reports",
            },
        ),
        migrations.AlterField(
            model_name="compliancereport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="UTC timestamp when this record was created",
            ),
        ),
        migrations.AlterField(
            model_name="compliancereport",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Download link expires after this time. File is purged.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="compliancereport",
            name="filters",
            field=models.JSONField(
                default=dict,
                help_text="Additional filters: event_type, actor_type, resource_type, agent_name, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="compliancereport",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier (UUIDv4, non-enumerable)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="compliancereport",
            name="summary",
            field=models.JSONField(
                default=dict,
                help_text="Computed summary: total_events, by actor_type breakdown, ai_agents_involved list, alert_count, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="compliancereport",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="UTC timestamp when this record was last modified"
            ),
        ),
    ]
