# Generated by Django 5.1.15 on 2026-10-08 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentinel_risk", "0004_unique_alert_per_rule_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
            },
        ),
        migrations.AlterModelOptions(
            name="alertrule",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Alert Rule",
                "verbose_name_plural": "Alert Rules",
            },
        ),
        migrations.AlterField(
            model_name="alert",
            name="audit_event_id",
            field=models.UUIDField(
                db_index=True, help_text="ID of the AuditEvent that triggered this alert."
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="UTC timestamp when this record was created",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier (UUIDv4, non-enumerable)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="notifications_sent",
            field=models.JSONField(
                default=list, help_text="List of notification delivery records."
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                help_text="The rule that fired this alert.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alerts",
                to="sentinel_risk.alertrule",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                help_text="Severity inherited from the rule at time of firing.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="UTC timestamp when this record was last modified"
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="condition",
            field=models.JSONField(
                help_text='Structured condition evaluated against AuditEvent fields. e.g. {"field": "risk_score", "operator": "gte", "value": 75}'
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="UTC timestamp when this record was created",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="What this rule detects and why it matters."
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier (UUIDv4, non-enumerable)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Inactive rules are not evaluated."
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="is_builtin",
            field=models.BooleanField(
                default=False, help_text="Built-in rules cannot be deleted, only deactivated."
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="name",
            field=models.CharField(
                help_text="Human-readable rule name. e.g. 'Critical risk score — AI agent'",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="notification_channels",
            field=models.JSONField(
                default=list, help_text="List of channels to notify: ['email', 'slack', 'webhook']"
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="notification_config",
            field=models.JSONField(
                default=dict,
                help_text='Channel-specific configuration. e.g. {"slack": {"webhook_url": "https://..."}, "email": {"to": ["..."]}}',
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="suppression_window_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Suppress duplicate alerts for the same rule+actor within this many minutes.",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="trigger_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of times this rule has fired."
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="UTC timestamp when this record was last modified"
            ),
        ),
    ]
